name: Welcome New Contributors

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs: 
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting message
        uses: actions/first-interaction@v1
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Thanks for your first issue!"
          pr-message: "🎉 Thanks for your first pull request!"
